### PR TITLE
#161039568 Build UI Page where a User can Sign In

### PR DESCRIPTION
**Pull request by andrewhingah**
**What does this PR do?**
Builds user interface page where a user (admin/attendant) can sign in.

**Description of tasks to be completed**
Create login page using HTML and CSS

**How should this be manually tested?**
Clone this repository
`git clone https://github.com/andrewhingah/storemanager.git`
Cd into the repository
Checkout to feature branch `git checkout ft-login-page-#161039568`
Open `index.html` on a browser.

**Any background content you want to provide?**
This is just a user interface page, the core functionality is yet to be implemented.

**What are the relevant Pivotal Tracker stories?**
#161039568

**Screenshots (If appropriate)**
screenshot from 2018-10-09 17-25-42

### CODE REVIEW

**Comment by JoshuaKodhe** [comment]
Real nice UI 
You could however substitute the signin button on the nav with some other link

**Comment by andrewhingah** [comment]
> Real nice UI
> You could however substitute the signin button on the nav with some other link

sure. Will do that

**Comment by kelvinrandu** [comment]
cool design
I dont see the importance of the navbar in the login page

**Comment by bryanmwaniqi** [comment]
the sign in nav item, change it sign up

**Comment by bryanmwaniqi** [comment]
nice ui overall

**Pull request merged**
