### PR TITLE
#161055075 Create Page for Adding Products to Buyer's Cart

### PR DESCRIPTION
**Pull request by andrewhingah**
**What does this PR do?**
Builds user interface page where a store attendant can add products to cart and create a sale record.

**Description of tasks to be completed**
Create UI page for adding products to cart

**How should this be manually tested?**
Clone this repository
`git clone https://github.com/andrewhingah/storemanager.git`
Cd into storemanager/ui
Checkout to feature branch `git checkout ft-add-products-to-cart-ui-#161055075`

Open `cart.html` on a browser.

**What are the relevant Pivotal Tracker stories?**
#161055075

**Screenshots**
screenshot from 2018-10-11 12-46-35

### CODE REVIEW

**Comment by Arusey** [comment]
Looks perfect

**Comment by bryanmwaniqi** [comment]
great color blending

**Comment by ogol254** [comment]
How do you expect add to cart to work in this scenario?

**Comment by andrewhingah** [comment]
> How do you expect add to cart to work in this scenario?

The attendant should search for a product from the list then click add to add to the cart on the right.

**Pull request merged**
